apiVersion: apps/v1
kind: Deployment
metadata:
    name: employee-deployment
    labels:
        app: employee
spec:
    replicas: 2
    selector:
        matchLabels:
            app: employee
    template:
        metadata:
            labels:
                app: employee
                service: employee
        spec:
            containers:
                -   name: employee-service
                    image: 'docker.io/library/k8s-springboot-discovery:0.0.1-SNAPSHOT'
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 8080

