apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    labels:
        app: postgres
spec:
    replicas: 2
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
                service: postgres
        spec:
            containers:
                -   name: postgres
                    image: 'postgres:latest'
                    env:
                        -   name: POSTGRES_DB
                            value: tayduong
                        -   name: POSTGRES_PASSWORD
                            value: secret
                        -   name: POSTGRES_USER
                            value: postgres
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    labels:
        app: postgres
spec:
    type: NodePort
    ports:
        -   port: 5432
            targetPort: 5432
            nodePort: 30007
            protocol: TCP
            name: 'http'
    selector:
        app: postgres
