networks:
    my_network:
        driver: bridge

services:
    postgres:
        image: 'postgres:latest'
        networks:
            - my_network
        environment:
            - 'POSTGRES_DB=tayduong'
            - 'POSTGRES_PASSWORD=secret'
            - 'POSTGRES_USER=postgres'
        ports:
            - '5432:5432'
    k8s-springboot-discovery:
        build: .
        networks:
            - my_network
        environment:
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tayduong'
            - 'SPRING_DATASOURCE_USERNAME=postgres'
            - 'SPRING_DATASOURCE_PASSWORD=secret'
        ports:
            - '8080:8080'
        depends_on:
            -   postgres
        links:
            -   postgres
