GET http://localhost:8080/employee/d09ef554-13b8-477c-a35d-559c7c7a5ff9
Accept: application/json

###
POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id = 99 &
content = new-element

###
POST http://localhost:80/api/item
Content-Type: application/json

{}

###
### GET request to example server
POST http://localhost:8080/employee?employeeName=tayduong
Content-Type: application/json

###

POST http://localhost:30008/employee?
    employeeName={{$random.alphanumeric(8)}}

###

GET http://localhost:30008/employee/aacb79b6-30d2-4115-b845-45a323032cbe
