GET http://localhost:8080/employee/d09ef554-13b8-477c-a35d-559c7c7a5ff9
Accept: application/json

###
POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id = 99 &
content = new-element

###
POST http://localhost:80/api/item
Content-Type: application/json

{}

###
### GET request to example server
POST http://localhost:8080/employee?employeeName=tayduong
Content-Type: application/json

###

POST http://localhost:30007/employee?employeeName=tuan

###

GET http://localhost:30007/employee/69b68f21-a92f-4b6f-b6c8-62763cb0e8e9

###

GET http://localhost:30007/employee

###

POST http://localhost:9090/employee?employeeName=quan