secretGenerator:
    -   name: postgres-secret
        literals:
            - POSTGRES_PASSWORD=secret
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tayduong

resources:
    - init-sql.yaml
    - postgres-deployment.yml
    - k8s-employee-deplay.yml