apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    labels:
        app: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: postgres
                service: postgres
        spec:
            containers:
                -   name: postgres
                    image: 'postgres:latest'
                    env:
                        -   name: POSTGRES_DB
                            valueFrom:
                                secretKeyRef:
                                    name: postgres-secret
                                    key: POSTGRES_DB

                        -   name: POSTGRES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: postgres-secret
                                    key: POSTGRES_PASSWORD

                        -   name: POSTGRES_USER
                            valueFrom:
                                secretKeyRef:
                                    name: postgres-secret
                                    key: POSTGRES_USER
                    ports:
                        -   containerPort: 5432
                            name: postgres
                    volumeMounts:
                        -   name: postgres-storage
                            mountPath: /var/lib/postgresql/data
            volumes:
                -   name: postgres-storage
                    persistentVolumeClaim:
                        claimName: postgres-pv-claim
                -   name: init-sql
                    configMap:
                        name: init-sql

---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    labels:
        app: postgres
spec:
    ports:
        -   port: 5432
#            targetPort: 5432
#            protocol: TCP
#            name: 'http'
    selector:
        app: postgres
    clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pv-claim
    labels:
        app: postgres
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi